version: "3"

services:
  db-postgres-empathy-api:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres-empathy-api"
    restart: always
    volumes:
      - ./banco-de-dados-empathy-api:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lauser
      POSTGRES_PASSWORD: lapassword

volumes:
  banco-de-dados-empathy-api: